[package]
name = "bitcoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
bitcoin_hashes = "0.12.0"
rand = "0.8.5"
chrono = "0.4"
