name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up apt-get
      run: |
        sudo sed -i 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' /etc/apt/sources.list
        sudo apt-get update
    - name: Install GTK
      run: sudo apt-get install -y libgtk-3-dev --fix-missing
    - name: Install glade
      run: sudo apt-get install -y glade --fix-missing
    - name: Install libgtk-3-doc
      run: sudo apt-get install -y libgtk-3-doc --fix-missing
    - name: Build
      run: cargo build --verbose
    - name: Run cargo check
      run: cargo check --verbose
    - name: Run cargo clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
