name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GTK
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
    - name: Install glade
      run: sudo apt-get update && sudo apt-get install -y glade
    - name: Install libgtk-3-doc
      run: sudo apt-get install -y libgtk-3-doc
    - name: Build
      run: cargo build --verbose
    - name: Run cargo check
      run: cargo check --verbose
    - name: Run cargo clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose